FROM ubuntu:18.04

WORKDIR /tmp/

ARG MT5_ACCOUNT
ARG MT5_PWD
ARG WINE_GECKO_VERSION=2.47
ARG WINE_MONO_VERSION=7.4.0

RUN set -ex; \
    dpkg --add-architecture i386; \
    DEBIAN_FRONTEND=noninteractive apt-get update -y; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    apt-transport-https \
    binutils \
    cabextract \
    curl \
    # To take screenshots of Xvfb display
    imagemagick \
    p7zip \
    software-properties-common \
    wget \
    unzip \
    xz-utils \
    xvfb \
    x11vnc \
    net-tools \
    gpg-agent \
    winbind \
    libvulkan1 

# Install Gecko and Mono
RUN apt-get update -y && \
    apt-get install -y wget && \
    mkdir -p /usr/share/wine/gecko && \
    wget "http://dl.winehq.org/wine/wine-gecko/${WINE_GECKO_VERSION}/wine_gecko-${WINE_GECKO_VERSION}-x86_64.msi" -O /usr/share/wine/gecko/wine_gecko-${WINE_GECKO_VERSION}-x86_64.msi && \
    chmod +x /usr/share/wine/gecko/wine_gecko-${WINE_GECKO_VERSION}-x86_64.msi && \
    mkdir -p /usr/share/wine/mono && \
    wget "http://dl.winehq.org/wine/wine-mono/${WINE_MONO_VERSION}/wine-mono-${WINE_MONO_VERSION}-x86.msi" -O /usr/share/wine/mono/wine-mono-${WINE_MONO_VERSION}-x86.msi && \
    chmod +x /usr/share/wine/mono/wine-mono-${WINE_MONO_VERSION}-x86.msi 

# Install wine
RUN set -ex; \
    wget -nc https://dl.winehq.org/wine-builds/winehq.key; \
    apt-key add winehq.key; \
    apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/; \
    DEBIAN_FRONTEND=noninteractive apt-get update -y; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --install-recommends \
    winehq-staging; \
    rm winehq.key

# Install winetricks
RUN set -ex; \
    wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks; \
    chmod +x winetricks; \
    mv winetricks /usr/local/bin

RUN set -ex; \
    wget https://www.python.org/ftp/python/3.9.9/python-3.9.9-amd64.exe; \
    chmod +x python-3.9.9-amd64.exe; 

COPY waitonprocess.sh \
    screenshot.sh \
    run_mt5.sh \
    run_vnc.sh \
    run_xvfb.sh \
    wine-init.sh \
    /docker/

RUN set -e; \
    chmod a+rx \
    /docker/waitonprocess.sh \
    /docker/screenshot.sh \
    /docker/run_mt5.sh \
    /docker/run_vnc.sh \
    /docker/run_xvfb.sh \
    /docker/wine-init.sh;

#Create user and set group
ARG USER=winer
ARG HOME=/home/$USER
ARG USER_ID=501
ENV USER=$USER \
    HOME=$HOME

RUN set -ex; \
    groupadd $USER; \
    useradd -u $USER_ID -d $HOME -g $USER -ms /bin/bash $USER; 

USER $USER

#Wine configuration
ENV WINEARCH=win64 \
    WINEPREFIX=$HOME/.wine \
    DISPLAY=:1 \
    SCREEN_NUM=0 \
    SCREEN_WHD=1366x768x24
ENV MT5DIR=$WINEPREFIX/drive_c/users/winer/AppData/Local/Programs/mt5
ENV PY_HOME=$HOME/.wine/drive_c/users/winer/AppData/Local/Programs/Python

USER $USER
RUN set -ex; \
    wine64 wineboot --init; \
    xvfb-run sh /docker/wine-init.sh;

RUN set -ex; \
    winetricks -q win10; wineserver -w\
    /docker/waitonprocess.sh wineserver;

RUN xvfb-run wine64 /tmp/python-3.9.9-amd64.exe /q;\
    /docker/waitonprocess.sh wineserver;

RUN xvfb-run wine64 msiexec /i /usr/share/wine/gecko/wine_gecko-${WINE_GECKO_VERSION}-x86_64.msi \
    /docker/waitonprocess.sh wineserver;

RUN xvfb-run wine64 msiexec /i /usr/share/wine/mono/wine-mono-${WINE_MONO_VERSION}-x86.msi  \
    /docker/waitonprocess.sh wineserver;

USER root
RUN mkdir -p /tmp/screenshots/; \
    chown winer:winer /tmp/screenshots/; \
    mkdir -p $HOME/git/algo-trade/; \
    chown -R winer:winer $HOME/git/;
    
USER $USER
WORKDIR $MT5DIR
VOLUME /tmp/screenshots/

ENTRYPOINT ["/bin/bash"]
#CMD ["/docker/run_mt5.sh"]
